replicaCount: 3

image:
  repository: acrdesafiogovbr.azurecr.io/meu-website
  tag: v0.4
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics
      port: 9100
      targetPort: 9100

createDeployment: true
createService: false
