name: Build Observability Infra With Terraform in Azure
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
  AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - terraform/observability-stack/*
jobs:
  Create-Observability-Terraform:
    name: Deploy Infra With Terraform in Azure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/observability-stack
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2.0.3
      - name: Terraform Init
        run: |
          echo "Iniciando o Terraform"
          terraform init -reconfigure
        continue-on-error: false
      - name: Terraform Format
        run: |
          echo "Identando o código"
          terraform fmt --recursive
        continue-on-error: true
      - name: Terraform Validate
        run: |
          echo "Validando a Sintax"
          terraform validate
        continue-on-error: false
      - name: Terraform Plan
        run: |
          echo "Planificando o que será provisionado"
          terraform plan
        continue-on-error: false
      - name: Terraform Apply
        run: |
          echo "Deploy Infra"
          terraform apply -auto-approve
        continue-on-error: false
