name: ACR and AKS Terraform Deploy

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
  AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
on:
  workflow_dispatch:

jobs:
  destroy-acr:
    name: Destroy Infra With Terraform in Azure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/main-stack
    permissions:
        id-token: write
        contents: read
        actions: read
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        run: terraform init
        continue-on-error: false

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        continue-on-error: false
